version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - nest-mongo-network
    env_file:
      - .env
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - '6006:3000'
    volumes:
      - ./src:/user/src/app/src
      - ignore:/user/src/app/node_modules/
    depends_on:
      - mongo
    networks:
      - nest-mongo-network
    env_file:
      - .env

volumes:
  ignore:


networks:
  nest-mongo-network:
    driver: bridge
