version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - nest-mongo-network
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:3000'
    volumes:
      - ./:/user/src/app
      - ignore:/user/src/app/node_modules/
    depends_on:
      - mongo
    networks:
      - nest-mongo-network
    env_file:
      - .env

volumes:
  ignore:

networks:
  nest-mongo-network:
    driver: bridge
