version: '3'
services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:3000'
    volumes:
      - ./:/user/src/app
      - ignore:/user/src/app/node_modules/
volumes:
  ignore:
