version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - nest-mongo-network
    env_file:
      - .env
    volumes:
      - dbdata:/data/db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    env_file:
      - .env
    volumes:
      - redis:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081" 
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: yarn start:dev
    ports:
      - '6006:3000'
    volumes:
      - ./src:/user/src/app/src
      - ignore:/user/src/app/node_modules/
    depends_on:
      - mongo
    networks:
      - nest-mongo-network
    env_file:
      - .env

volumes:
  ignore:
  dbdata:
  redis:
    driver: local


networks:
  nest-mongo-network:
    driver: bridge
