version: '3'
services:
  postgres:
    image: postgres:15.2
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6.21
    networks:
      - postgres
    ports:
      - '8008:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:3000'
    volumes:
      - ./:/user/src/app
      - ignore:/user/src/app/node_modules/
    depends_on:
      - postgres
    networks:
      - postgres
    env_file:
      - .env

volumes:
  ignore:

networks:
  postgres:
    driver: bridge
